### ISSUE TITLE
'InAppWebView' has different definitions in different modules

### ISSUE THREAD

**Issue by norman93sun** [talkjs/talkjs-examples#536] opened 2024-06-17 06:35 UTC
Hi there, i'm getting this error when using Flutter SDK,

Only added this `flutter_inappwebview: ^6.0.0` to yaml.
 

<img width="1390" alt="截屏2024-06-17 14 32 49" src="https://github.com/talkjs/talkjs-examples/assets/18303855/b2c60553-2771-4d36-a0fb-b4cb74a3b0db">

**Comment by vickz84259** [comment] 2024-06-27 10:37
Hey there, we have noted the issue and are currently investigating it. I'll get back to you once we have shipped a fix for this.

**Comment by vickz84259** [comment] 2024-06-27 14:56
I'd like to provide you with an update. We have fixed the cause of the conflict between our SDK and the `flutter_inappwebview` package. Please upgrade to version `0.12.1` of the `talkjs_flutter` package.

Should you encounter any other issues, feel free to reach out via our [livesupport](https://talkjs.com/?chat). My apologies for the inconvenience that this issue caused.

**Closed by vickz84259** 2024-06-27 14:56 UTC
