### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'postMessage')

### ISSUE THREAD

**Issue by Frosty21** [talkjs/talkjs-examples#296] opened 2022-05-19 19:52 UTC
Hi there,
My team is having this error creeping up and was wondering if you could clarify on this as it is not in `talk.types.d.ts` for postMessage. 
Updated after bumping TalkJS from "^0.15.2" to "^0.15.4" error issue is no more. please update this in the readme [changelogs](https://changelog.talkjs.com/) cheers

```ts
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'postMessage')
    at u (talk.js:18:5962)
    at Object.r (talk.js:18:5434)
    at talk.js:18:58215
u @ talk.js:18
r @ talk.js:18
(anonymous) @ talk.js:18
Promise.then (async)
post @ talk.js:18
t.onWindowVisibleChanged @ talk.js:18
n @ talk.js:18
(anonymous) @ talk.js:18
```
[uncaught error with reading PostMessage.log](https://github.com/talkjs/talkjs-examples/files/8733649/uncaught.error.with.reading.PostMessage.log)

**Comment by eteeselink** [comment] 2022-05-20 07:27
Hi there, 

Just to clarify, are you still experiencing this bug or has this been resolved?

We did recently fix a bug that may have caused this error message. The fix was in cloud-served code however, so updating the npm package version should have not affected that. It's possible, however, that you updated to the new version around the same time as shipped said bugfix. 

We'll try to be better at including exhaustive bug fixes in the changelog, thanks for that suggestion.

**Comment by Frosty21** [comment] 2022-05-21 04:52
Yep it’s all fixed I just wanted to document it if someone has the same issue. 
If you can update it into the change log that would be awesome cheers. 
Another question is there a way to disable the warning message from the newest version?

**Comment by eteeselink** [comment] 2022-05-21 20:09
Which warning message are you referring to, in particular? Can you eg show a screenshot with the devtools console open or something like that? Thanks

**Comment by eteeselink** [comment] 2022-05-24 07:34
thanks! this looks like it may be another bug altogether. we'll look into it.

**Comment by eteeselink** [comment] 2022-05-24 07:37
Can you give me some more context maybe?
- Does it happen consistently or sometimes?
- Does it happen when the chat UI loads immediately, or after doing a particular user action?

If you have a live (staging) app that we could navigate to to try to reproduce this, that'd be extremely helpful. If there's private credentials to share, consider using the live support chat on our website (https://talkjs.com) or emailing to dev@talkjs.com

Thanks!

**Comment by Frosty21** [comment] 2022-05-25 05:46
I've engaged with the live support chat just then. Its when we are in local environment the modal for talkJS chat box goes blank with warn error message whereas development in AWS   works fine with no warn error message or black talkjs chat box modal...

**Comment by eteeselink** [comment] 2022-05-25 07:55
Thanks, we'll continue the conversation on the chat.

**Comment by bigblind** [comment] 2022-05-25 08:51
Closing this issue since your initial problem has been solved. We'll continue the discussion about the warning in support chat .

**Closed by bigblind** 2022-05-25 08:51 UTC

**Comment by Frosty21** [comment] 2022-06-01 04:22
Oh man my team figured out the issue it was on our side our default image wasn't rendering for the photoUrl...
What was weird though was that logzio error reporting only give it as a code 2 error but when console.log(error) the error was visible. We'll probably transform the error so its readable on logzio but something for your team to consider as a use case with the error messages.
The newest version of talkjs 0.15.4 is working fine

**Comment by michaelaflores** [comment] 2022-06-21 05:54
I see this issue in 0.15.5 when I recreate the [basic react example](https://github.com/talkjs/talkjs-examples/blob/master/react/basic-example/src/index.js) or [NextJS example](https://talkjs.com/resources/add-chat-to-a-next-js-app-with-talkjs-tutorial/). It causes the chat box to not appear on first load. Strangely, after the initial mount cycle, if I then change some code to cause a HMR, the chat box then appears. Here is the [code](https://gist.github.com/michaelaflores/3b8b30da41f7b72e730c6a7b19d71f90) (just the one file)

**Comment by shindeajinkya** [comment] 2022-09-27 08:02
@michaelaflores found any solution to issue you are facing? facing same issue, tried using 0.15.4, still same issue is there, first load it gives this error in console `TypeError: Cannot convert undefined or null to object`

![image](https://user-images.githubusercontent.com/51527913/192469030-839b5b8e-3516-4704-9c6f-57b7d0d5743c.png)

**Comment by bigblind** [comment] 2022-09-27 10:51
Hi there. We think this issue is caused by the way our examples initialize everything when the component is mounted using `useEffect`, but then don't clean it up when the component is unmounted, so if the component gets unmounted and remounted again, this code is run twice, and something goes wrong. We're going through our docs and examples, and updating them, but in the meantime, have a look at this codesandbox, and see if changing your code like this fixes the issue for you:

https://codesandbox.io/s/vigilant-varahamihira-sr4heb?file=/src/App.js
